Mysql:
  ip: localhost
  port: 3306
  databaseGlobal: perfect
  databaseServer: rankup
  user: root
  password: 123456

Mongo:
  ip: localhost
  port: 27017
  user: perfect
  password: 12345
  databaseGlobal: perfect
  databaseServer: rankup

Redis:
  ip: localhost
  port: 6379
  password: 12345
